package sanchez.sanchez.sergio.domain.models;

/**
 * Alert Category Enum
 */
public enum AlertCategoryEnum {
    DEFAULT, INFORMATION_KID, GENERAL_STATISTICS, STATISTICS_KID, INFORMATION_EXTRACTION,
    APPS_INSTALLED, TERMINALS, GEOFENCES, CONTACTS, KID_REQUEST,
    PHONE_NUMBERS, FUN_TIME, SCHEDULED_BLOCK
}
